//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_EA.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDT_DBEntities : DbContext
    {
        public GDT_DBEntities()
            : base("name=GDT_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Func> Funcs { get; set; }
        public virtual DbSet<InputParam> InputParams { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<QuickSearch> QuickSearches { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
    }
}
