//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_EA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputParam
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public int FuncId { get; set; }
    
        public virtual Func Func { get; set; }
        public virtual Type Type { get; set; }
    }
}
