//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_EA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public int Qualifier { get; set; }
        public int SearchInfoId { get; set; }
        public string Value { get; set; }
        public bool IsPointer { get; set; }

        public virtual QuickSearch QuickSearch { get; set; }
        public virtual Type Type { get; set; }
    }
}
